export const ringsProduct = [
    {
      image: "goldring.webp",
      name: "Dune Quadra Stack - 18K",
      originalPrice: "Rs.2,599.00 PKR",
      salePrice: "Rs.1,799.00 PKR",
      tag: "Sale",
    },
    {
      name: "Iced Out Luxe Zircon Ring - 18K",
      originalPrice: "Rs.1,999.00 PKR",
      salePrice: "Rs.1,699.00 PKR",
      tag: "Sale",
      image: "goldring.webp",
    },
    {
      name: "Irregular Baroque Pearl Ring - 18K",
      originalPrice: "Rs.2,599.00 PKR",
      salePrice: "Rs.2,199.00 PKR",
      tag: "Sale",
      image: "goldring.webp",
    },
    {
      name: "Link Up Ring - 18K",
      originalPrice: "Rs.2,199.00 PKR",
      salePrice: "Rs.1,699.00 PKR",
      tag: "Sale",
      image: "goldring.webp",
    },
    {
      name: "Lea Baguette X Curb Ring",
      originalPrice: "Rs.2,699.00 PKR",
      salePrice: "Rs.2,199.00 PKR",
      tag: "Sale",
      image: "goldring.webp",
    },
    {
      image: "goldring.webp",
      name: "Dune Quadra Stack - 18K",
      originalPrice: "Rs.2,599.00 PKR",
      salePrice: "Rs.1,799.00 PKR",
      tag: "Sale",
    },
    {
      name: "Iced Out Luxe Zircon Ring - 18K",
      originalPrice: "Rs.1,999.00 PKR",
      salePrice: "Rs.1,699.00 PKR",
      tag: "Sale",
      image: "goldring.webp",
    },
    {
      name: "Irregular Baroque Pearl Ring - 18K",
      originalPrice: "Rs.2,599.00 PKR",
      salePrice: "Rs.2,199.00 PKR",
      tag: "Sale",
      image: "goldring.webp",
    },
    {
      name: "Link Up Ring - 18K",
      originalPrice: "Rs.2,199.00 PKR",
      salePrice: "Rs.1,699.00 PKR",
      tag: "Sale",
      image: "goldring.webp",
    },
    {
      name: "Lea Baguette X Curb Ring",
      originalPrice: "Rs.2,699.00 PKR",
      salePrice: "Rs.2,199.00 PKR",
      tag: "Sale",
      image: "goldring.webp",
    },
  ];